### ISSUE TITLE
Global state leakage

### ISSUE THREAD

**Issue by jmerrifield** [twitter/twitter-cldr-npm#9]
Hi, we run this module in a Node.js web server, that handles high traffic, and each request can potentially have a different associated locale. Since updating to 2.x we've started experiencing occasional instances of the wrong date/time formatting being applied. Digging a little deeper, I believe there to be a global state leakage issue with the current release. The following is from a Node.js repl:

```js
> var t1 = require('twitter_cldr').load('en')
undefined
> var t2 = require('twitter_cldr').load('hi')
undefined
> new t1.DateTimeFormatter().format(new Date(), {type: 'full'})
'मंगलवार, 21 जून 2016 को 11:45:30 पूर्वाह्न UTC-08:00'
> new t2.DateTimeFormatter().format(new Date(), {type: 'full'})
'मंगलवार, 21 जून 2016 को 11:59:43 पूर्वाह्न UTC-08:00'
```

I would expect the `DateFormatter` of `t1` to return an 'en' formatted date string.

@erikogan @pchew-change

**Comment by web-padawan** [comment]
When calling `load`, there are two steps: 
1. Required locale bundle is loaded to global variable named `TwitterCldrDataBundle`.
2. Settings are updated using `set_data()`, which looks like this:  `TwitterCldr.data = bundle;`

Modifying this is likely to be a breaking change.
But it would be nice to keep loaded locale bundles instead of replacing them. 
For now, we have to do it ourselves using some build / modular tools.

**Comment by jmerrifield** [comment]
I just realized this issue should probably be against [twitter/twitter-cldr-js](https://github.com/twitter/twitter-cldr-js). Would you like me to close this and file it there instead?

**Comment by arnavk** [comment]
Yes, that'd be great. Thanks! 

Would you like to give fixing this a shot? If not, I can try to get to it as soon as I possibly can
